# Generated by Django 4.2.4 on 2023-08-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
