# Generated by Django 4.2.4 on 2023-08-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
